### ISSUE TITLE
在windows下面测试，如果同时开上几个浏览器不断刷新进行连接会卡死

### ISSUE THREAD

**Issue by wangat** [dimiro1/ipe#32]
2016/08/27 02:26:14 http: response.WriteHeader on hijacked connection
2016/08/27 02:26:14 http: response.Write on hijacked connection

![image](https://cloud.githubusercontent.com/assets/11567857/18016348/7bdb8b20-6bfe-11e6-99db-8f02d2ca6810.png)

我不太懂英文，所以没办法用英文交流，很抱歉，希望可以解决

**Comment by dimiro1** [comment]
@wangat 
我没有一个Windows机器进行测试。我怀疑是错误在网络挂接功能。您可以禁用网络挂接和验证，如果错误仍然存在？ 谢谢。

**Comment by dimiro1** [comment]
@wangat I am closing the issue. Feel free to reopen.
