### ISSUE TITLE
cross compilation / build

### ISSUE THREAD

**Issue by funsterisdafunniest** [dimiro1/ipe#34]
Hi, i saw on the readme that you can't provide windows relase since you didn't own a windows machine, but as referenced in [this blog post](http://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5) that it is possible to do a cross build for other os and architecture.

i've tried it myself, and ipe seems to run okay on windows (didn't have a chance to test the functionality, since it's on a friend's computer). Is there any possibilty to add the windows release for future release? or is there any problem with compiling it that way? (I'm sorry if this sounds stupid, i'm just starting to learn go lang)

**Comment by dimiro1** [comment]
Yes, I do not have a Windows machine to make some unit and functional tests. Before each release I have at least to run the manual functional test suite [1].

[1] https://github.com/dimiro1/ipe/tree/master/functional

**Comment by funsterisdafunniest** [comment]
aa i see, thanks for the explanation,
i think i'll close the issue now. thx
