### ISSUE TITLE
triggerHook issue

### ISSUE THREAD

**Issue by rtatibouet** [dimiro1/ipe#37]
Hello, 
I have an issue with the webhooks functionnality. Ipê works like a charm when it is set to false.
However, when set to true, event is well sent, I even have a response from the server, but I have the following error message in the logs :

> goroutine 34 [running]:
> runtime/debug.Stack(0x774a00, 0x0, 0x0)
> 	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
> runtime/debug.PrintStack()
> 	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
> github.com/pressly/chi/middleware.Recoverer.func1.1(0xc4200d00f0, 0x9770c0, 0xc420120410)
> 	/home/ronan/go_work/src/github.com/pressly/chi/middleware/recoverer.go:25 +0x12d
> panic(0x76e1e0, 0xc42017a150)
> 	/usr/local/go/src/runtime/panic.go:458 +0x243
> github.com/rtatibouet/ipe/ipe.triggerHook(0x9779c0, 0xc420016780, 0xc42012c080, 0x7d69b4, 0xc, 0xc4200ccf00, 0x13, 0x0, 0x0, 0x0, ...)
> 	/home/ronan/go_work/src/github.com/rtatibouet/ipe/ipe/webhooks.go:206 +0x25b
> github.com/rtatibouet/ipe/ipe.(*app).TriggerMemberAddedHook(0xc42012c080, 0xc42001cb00, 0xc42000de90)
> 	/home/ronan/go_work/src/github.com/rtatibouet/ipe/ipe/webhooks.go:123 +0x1b9
> github.com/rtatibouet/ipe/ipe.(*channel).Subscribe(0xc42001cb00, 0xc42012c080, 0xc420016420, 0xc42001c980, 0x36, 0x0, 0x0)
> 	/home/ronan/go_work/src/github.com/rtatibouet/ipe/ipe/channel.go:108 +0x4cc
> github.com/rtatibouet/ipe/ipe.(*app).Subscribe(0xc42012c080, 0xc42001cb00, 0xc420016420, 0xc42001c980, 0x36, 0xc42012c080, 0x1)
> 	/home/ronan/go_work/src/github.com/rtatibouet/ipe/ipe/app.go:274 +0x53
> github.com/rtatibouet/ipe/ipe.onSubscribe(0xc420096780, 0xc4200ccca0, 0x12, 0xc42012c080, 0xc420014600, 0xf1, 0x600)
> 	/home/ronan/go_work/src/github.com/rtatibouet/ipe/ipe/websocket.go:228 +0x472
> github.com/rtatibouet/ipe/ipe.handleMessages(0xc420096780, 0xc4200ccca0, 0x12, 0xc42012c080)
> 	/home/ronan/go_work/src/github.com/rtatibouet/ipe/ipe/websocket.go:56 +0x4ad
> github.com/rtatibouet/ipe/ipe.(*websocketHandler).ServeHTTP(0xc4201284d0, 0x9770c0, 0xc420120410, 0xc4200d00f0)
> 	/home/ronan/go_work/src/github.com/rtatibouet/ipe/ipe/websocket.go:289 +0x339
> github.com/rtatibouet/ipe/ipe.(*websocketHandler).ServeHTTP-fm(0x9770c0, 0xc420120410, 0xc4200d00f0)
> 	/home/ronan/go_work/src/github.com/rtatibouet/ipe/ipe/ipe.go:51 +0x48
> net/http.HandlerFunc.ServeHTTP(0xc4201284c0, 0x9770c0, 0xc420120410, 0xc4200d00f0)
> 	/usr/local/go/src/net/http/server.go:1726 +0x44
> github.com/pressly/chi.(*Mux).routeHTTP(0xc420136180, 0x9770c0, 0xc420120410, 0xc4200d00f0)
> 	/home/ronan/go_work/src/github.com/pressly/chi/mux.go:386 +0x216
> github.com/pressly/chi.(*Mux).(github.com/pressly/chi.routeHTTP)-fm(0x9770c0, 0xc420120410, 0xc4200d00f0)
> 	/home/ronan/go_work/src/github.com/pressly/chi/mux.go:325 +0x48
> net/http.HandlerFunc.ServeHTTP(0xc4201284e0, 0x9770c0, 0xc420120410, 0xc4200d00f0)
> 	/usr/local/go/src/net/http/server.go:1726 +0x44
> github.com/pressly/chi/middleware.Recoverer.func1(0x9770c0, 0xc420120410, 0xc4200d00f0)
> 	/home/ronan/go_work/src/github.com/pressly/chi/middleware/recoverer.go:32 +0x9f
> net/http.HandlerFunc.ServeHTTP(0xc4201322a0, 0x9770c0, 0xc420120410, 0xc4200d00f0)
> 	/usr/local/go/src/net/http/server.go:1726 +0x44
> github.com/pressly/chi.(*Mux).ServeHTTP(0xc420136180, 0x9770c0, 0xc420120410, 0xc4200d00f0)
> 	/home/ronan/go_work/src/github.com/pressly/chi/mux.go:79 +0x1f2
> net/http.serverHandler.ServeHTTP(0xc42012c100, 0x9770c0, 0xc420120410, 0xc42016c000)
> 	/usr/local/go/src/net/http/server.go:2202 +0x7d
> net/http.(*conn).serve(0xc42012c180, 0x977940, 0xc4201343c0)
> 	/usr/local/go/src/net/http/server.go:1579 +0x4b7
> created by net/http.(*Server).Serve
> 	/usr/local/go/src/net/http/server.go:2293 +0x44d
> 2017/01/23 12:25:45 http: response.WriteHeader on hijacked connection
> 2017/01/23 12:25:45 http: response.Write on hijacked connection

I've tracked down a bit the time where the error is appearing. Everything is going fine until "done <- true", line 198. Then, the program "hangs" a bit, ctx.Done() is fired, and then the error occurs.

**Comment by dimiro1** [comment]
Thank you. I will take a look.
