### ISSUE TITLE
Add a production ready Dockerfile

### ISSUE THREAD

**Issue by dimiro1** [dimiro1/ipe#45]
Should we load the config with only one app and load the secrets with env vars?

**Comment by bmartel** [comment]
You may want to look at possibly abstracting both and handling them with https://github.com/spf13/viper. This would keep both secret env vars and any configuration files you need to depend on available through a unified api within the code. This would open up many more possibilities with how the application itself can be deployed or managed within a container, or in really any scenario.

**Comment by dimiro1** [comment]
Hey, @bmartel thanks for your comment. How to handle multiple applications using only env vars?

**Comment by dimiro1** [comment]
Hey, @bmartel I just merged #46 which adds a Dockerfile to the project, however, I still like your suggestion to use Viper to configure the application. Feel free to open a PR with the Viper implementation, I will be more than happy to accept it.
