### ISSUE TITLE
Why do we need to run functional/client.go manually?

### ISSUE THREAD

**Issue by ycgambo** [dimiro1/ipe#50]
There is a `webhooks` config option in `config.yml` file, but I don't see it starts automatically in `main.go`.
I compile and run ipe from go command line,  didn't execute any docker command or bash script.
I need to manually run functional/client.go to handle client auth connections.
Did I do it wrong? Is there other options?

**Comment by dimiro1** [comment]
`functional/client.go` was created with the only purpose to execute functional tests against the official Pusher javascript client. You don't need to execute this file if your only goal is to use the application.

**Comment by ycgambo** [comment]
You mean I can register related routes and authenticate channels even in php?

**Comment by dimiro1** [comment]
You can just start the `ipe` binary and use the official client libraries from Pusher. You just have to change the settings in the client libraries to point to `ipe` endpoint.

**Comment by ycgambo** [comment]
got it. I’ll try and document it on this issue several days later. happy Chinese new year～
