### ISSUE TITLE
Future of this package

### ISSUE THREAD

**Issue by fridzema** [dimiro1/ipe#51]
I am looking for a pusher replacement package at the moment when i came across this one. 
It looks like the development was very active a year ago but seems it stopped there. 

Just asking if it is abandoned and i must look further, or can i safely use this in production?

**Comment by dimiro1** [comment]
Since I am not running in production anymore I don't have plans to add new features. 

You could use it in production, but, at your own risk. 

I am open to reviewing any contribution coming from the community, feel free to send any PR with anything you find.

Thanks for your interest.
