### ISSUE TITLE
Presence channels subscribe fails with int userID

### ISSUE THREAD

**Issue by EdgarSedov** [dimiro1/ipe#55]
Hi, is there a way we could process integer as userId on channel subscribe [here](https://github.com/dimiro1/ipe/blob/ea6e116836c09f6edb7bd6dbb06e1eb6c28a05b7/channel/channel.go#L167)?
If u'll point me in right direction i can submit PR
My current problem is that my vendor (laravel) provides this key as int, and i can only affect userInfo field inside my project source files, so i'm hitting this err
`8 channel.go:174] json: cannot unmarshal number into Go struct field .user_id of type string`

**Comment by EdgarSedov** [comment]
Please take a look when u'll have time @dimiro1

**Comment by dimiro1** [comment]
@EdgarSedov Sorry for the super late response. Unfortunately we cannot do much, the protocol v7 from Pusher states that the `user_id` must be a String. https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol/#pusher_internalmember_added-pusher-channels-greater-client
