### ISSUE TITLE
Use secure connection for Ipe server

### ISSUE THREAD

**Issue by HeadacheMan** [dimiro1/ipe#8]
Hi, not sure if it's an issue but.. is it possible to use a secure connection for the Ipe server? If so, how can I configure it? I couldn't find it anywhere.

**Comment by dimiro1** [comment]
It is not implemented yet, but could be very easy to implement. Basically this could be implemented in https://github.com/dimiro1/ipe/blob/master/ipe/ipe.go#L34 changing the call for ListenAndServe to ListenAndServeTLS https://golang.org/pkg/net/http/#ListenAndServeTLS and adding the necessary configurations (It have to be implemented) in config file.

**Comment by dimiro1** [comment]
@HeadacheMan It is now implemented on master branch, please take a look :)
